Repository AJCandfield/boga-quotes, pull requests merged in 2024-06, with the labels that each got.

#1 feat: Setup
  .github/dependabot.yml
  .gitignore
  .pre-commit-config.yaml
  .pyproject.toml
  .python-version
  dependabot.yml
Labels: enhancement, major

#5 Setup `poetry`
  .pre-commit-config.yaml
  .pyproject.toml
  README.md
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement, minor

#7 Basic FastAPI server
  boga_quotes/__init__.py
  boga_quotes/main.py
  pyproject.toml
Labels: enhancement, patch

#9 Dockerfile
  .gitignore
  .pre-commit-config.yaml
  Dockerfile
  README.md
  compose.yml
Labels: enhancement, patch

#12 Releases
  .github/release.yml
  .github/workflows/semver.yml
Labels: enhancement, minor
